version: '3.8'
services:
  # PostgreSQL Database Service
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres  # Default username
      POSTGRES_PASSWORD: sawraj  # Default password
      POSTGRES_DB: Authentication  # Default database name
    ports:
      - "5432:5432"  # Expose port 5432 on the host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data to a volume

  # Backend Service
  backend:
    build: ./backend  # Path to backend Dockerfile
    container_name: backend
    ports:
      - "5000:5000"  # Expose backend port 5000
    depends_on:
      - db  # Backend depends on the database
    environment:
      DATABASE_URL: "postgresql://postgres:sawraj@db:5432/Authentication?schema=public"  # Connection string

  # Frontend Service
  frontend:
    build: ./frontend  # Path to frontend Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"  # Expose frontend port 3000
    depends_on:
      - backend  # Frontend depends on the backend

# Define a volume for PostgreSQL data persistence
volumes:
  postgres_data: