import {
  Eye,
  EyeOff,
  Loader2,
  Facebook,
  Mail,
  type Icon as LucideIcon,
  Eraser,
  Settings,
  Laptop,
  Shirt,
  User2,
  ArrowBigLeft,
  MoveLeft,
  Search,
  ChevronLeft,
  ChevronRight,
  ArrowUpDown,
  RefreshCcw,
  ArrowUp,
  ArrowDown,
  MoreHorizontal,
  Asterisk,
  ArrowBigLeftDash,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  eye: Eye,
  eyeOff: EyeOff,
  spinner: Loader2,
  facebook: Facebook,
  google: Mail,
  mail: Mail,
  error: Eraser,
  check: Settings,
  laptop: Laptop,
  shirt: Shirt,
  user: User2,
  backBtn: MoveLeft,
  search: Search,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowUpDown: ArrowUpDown,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  refresh: RefreshCcw,
  moreHorizontal: MoreHorizontal,
  asterisk: Asterisk,
  ArrowBigLeftDash: ArrowBigLeftDash,
  moveLeft: MoveLeft,
};
